### ISSUE TITLE
Print Styles

### ISSUE THREAD

**Issue by jdsteinbach** [nternetinspired/jekyll-resume#1]
Looks like this project could use a better print stylesheet. See attached img for Chrome's attempt to format for print. 

Sorry this is just an issue & not a PR with a solution - I'm just about to reformat / publish an HTML version of my resume for the 1st time (possibly using this tool) and will send a PR w/ updated print CSS if I get that far. Thanks!

**Comment by nternetinspired** [comment]
Agreed! In fact it could do with print styles, period, there are none currently. 

It's added to my todo list now. Thanks.

**Comment by rightsaidjames** [comment]
+1 

I might fork this in order to redo my CV (long overdue) and if so I'll see what I can do with the print CSS.

**Comment by nternetinspired** [comment]
@rightsaidjames I've added some @print basics, removing _some_ print oddities, but there's still some outstanding issues with print. If you do make any improvements please cc me. Cheers :)
